services:
  mongo_db:
      image: mongo
      container_name: "mongo_db"
      restart: always    
      ports:
        - "27017:27017"
      volumes:
      - dbdata:/data/db

  poll-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: poll-app
    ports: 
      - "${API_PORT}:8000"
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - .env
    environment:
      - MONGODB_URL=mongodb://mongo_db
    volumes:
      - ./app/:/app/
    depends_on:
      - mongo_db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo_db
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_DB_ADMIN_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_DB_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://mongo_db:27017/ 
    depends_on:
      - mongo_db

volumes:
  dbdata:
