name: Continuous Integration 

on:
  push:

  pull_request:
    branches:
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Setup environment variables
      run: cp .env.example .env

    - name: Build and run Docker Compose
      run: docker compose up -d --build

    - name: Run tests
      run: docker compose exec poll-app pytest

    - name: Shut down Docker Compose
      run: docker compose down
