name: Continuous Integration 

on:
  push:

  pull_request:
    branches:
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Setup environment variables
      run: |
        echo HOST=http://127.0.0.1 > ./app/.env
        echo API_PORT=8000 >> ./app/.env
        echo MONGODB_URL=mongodb://mongo_db >> ./app/.env
        echo MONGO_DB_PORT=27017 >> ./app/.env

    - name: Build and run Docker Compose
      run: docker compose --env-file ./app/.env up -d --build

    - name: Run tests
      run: docker compose --env-file ./app/.env exec poll-app pytest

    - name: Shut down Docker Compose
      run: docker compose down
